Imported Upstream version 2.4.1+dfsg

diff --git a/build/MacOSX/Makefile.in b/build/MacOSX/Makefile.in
--- a/build/MacOSX/Makefile.in
+++ b/build/MacOSX/Makefile.in
@@ -168,6 +168,8 @@ MAC_APP_DIR = MonoDevelop.app
 MACOS = $(MAC_APP_DIR)/Contents/MacOS
 MAC_APP_LIB_DIR = $(MACOS)/lib/monodevelop
 ADDINS = $(MACOS)/lib/monodevelop/AddIns
+EXTRAS = $(top_srcdir)/../extras
+ARTIFACTS = $(top_srcdir)/../../artifacts
 CLEANFILES = MonoDevelop.dmg MonoDevelop.app
 #DISTCLEANFILES = 
 EXTRA_DIST = dmg-bg.png DS_Store Info.plist.in make-dmg-bundle.sh mdtool monodevelop 
@@ -358,6 +360,7 @@ MonoDevelop.app:
 	sed -e "s/@BUNDLE_VERSION@/$(BUNDLE_VERSION)/" -e "s/@ASSEMBLY_VERSION@/$(ASSEMBLY_VERSION)/" Info.plist.in > $(MAC_APP_DIR)/Contents/Info.plist
 	cp ../../theme-icons/Mac/*.icns $(MAC_APP_DIR)/Contents/Resources/
 	cp monodevelop $(MACOS)/monodevelop
+	cp mono-version-check $(MACOS)/mono-version-check
 	cp mdtool $(MACOS)/mdtool
 
 # copy monodevelop.pc and mono-addins.pc to Contents/MacOS/lib/pkgconfig
@@ -373,7 +376,6 @@ MonoDevelop.app:
 # Remove addins that don't work on OSX
 	rm -rf  $(ADDINS)/GnomePlatform* \
 	  $(ADDINS)/WindowsPlatform* \
-	  $(ADDINS)/MonoDevelop.GtkCore* \
 	  $(ADDINS)/MonoDevelop.Gettext/*
 
 # remove stuff we don't need
@@ -384,19 +386,33 @@ MonoDevelop.app:
 	  $(MACOS)/lib/monodevelop/bin/repository-cache* \
 	  $(MACOS)/lib/monodevelop/AddIns/MonoDevelop.TextTemplating/Mono.TextTemplating.Tests*
 
+# add extras known to work on Mac, if they exist
+	for ADDIN in MonoDevelop.IPhone MonoDevelop.MonoMac MonoDevelop.Database; do \
+		(ls $(EXTRAS)/$${ADDIN}/build/* > /dev/null 2>&1 && \
+			echo "Copying $${ADDIN}" && \
+			mkdir -p $(MAC_APP_LIB_DIR)/AddIns/$${ADDIN} && \
+			cp -pR $(EXTRAS)/$${ADDIN}/build/* $(MAC_APP_LIB_DIR)/AddIns/$${ADDIN}/ ) \
+		|| (echo "Skipping $${ADDIN}" && echo "$${ADDIN}" >> missing-stuff)  ; \
+	done
+
+# add the binary artifacts if they exist
+	mkdir -p $(MACOS)/lib/{moonlight,pkgconfig}
+	mkdir -p $(MACOS)/MonoDoc.app/
+	test ! -d $(ARTIFACTS)/MoonSDK ||  cp -pR $(ARTIFACTS)/MoonSDK/* $(MACOS)/lib/moonlight/
+	test ! -d $(ARTIFACTS)/MonoDoc.app ||  cp -pR $(ARTIFACTS)/MonoDoc.app/* $(MACOS)/MonoDoc.app/
+
 # update revision in updateinfo
-	if test -d ../../.git/svn; then svn_info="git log --no-color --first-parent -n1 --grep=git-svn-id: --pretty=format:%b | sed -n -e 's,git-svn-id: \(.*\)@\(.*\) .*,URL: \1 Revision: \2,p'"; fi; \
-	if test -d ./../../.svn; then svn_info='svn info'; fi; \
-	if test -n "$$svn_info"; then \
-		version=$$(cd ../..; \
-			LANG=C; export LANG; \
-			eval $$svn_info | sed -n -e '/Last Changed Rev/ s/.*: //p'; \
-		); \
-		echo "a3140c14-ef90-4019-ae6c-9d93804d6611 $$version" > "$(MACOS)/updateinfo"; \
-	fi;
+	echo "a3140c14-ef90-4019-ae6c-9d93804d6611 $$(cat release-info)" > "$(MACOS)/updateinfo"
 
 # touch the directory so that update dependencies work
 	touch MonoDevelop.app
+
+	@echo ""
+	@echo "MONODEVELOP RELEASE: $$(cat release-info)"
+	@echo "$$(cat ../../vcrevision)"
+	@if test -f missing-stuff; then echo ""; echo "Missing stuff:"; cat missing-stuff; fi
+	@echo ""
+	@rm -f missing-stuff
 
 MonoDevelop.app.zip: MonoDevelop.app
 	zip -r9uq MonoDevelop.app.zip MonoDevelop.app
